# Site Settings
title: Ram Prabhakar
first_name: Ram
middle_name:
last_name: Prabhakar
email: xxxx@dsai.iitm.ac.in
description: Assistant Professor, DSAI, IIT Madras
footer_text: >
  © 2025 Ram Prabhakar
icon: "⚡️"
url: https://kramprabhakar.github.io
baseurl: "/al-folio-test"
last_updated: true

# Scholar
scholar_userid: gBhmvr8AAAAJ
semanticscholar_id:

# Social
github_username:
linkedin_username:
twitter_username:
orcid_id:

# Analytics
google_analytics:

# Theme / Layout
navbar_fixed: false
footer_fixed: false
search_enabled: true
bib_search: true
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_publication_thumbnails: true
enable_publication_badges: true
enable_math: true
enable_tooltips: false

# Blog
blog_name:
blog_description:
permalink: /blog/:year/:title/
lsi: false
future: false

# Collections
collections:
  news:
    defaults:
      layout: post
    output: false
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page

# Jekyll Scholar
scholar:
  last_name: [Prabhakar]
  first_name: [Ram, R.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
    - superscript
    - latex
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

# Jekyll Archives
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

# Jekyll settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  style: compressed

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - readme_preview/
  - UPGRADING.md
  - vendor

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jemoji

# Third Party Libraries
third_party_libraries:
  download: false
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.1/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"
  chartjs:
    integrity:
      js: "sha256-0q+JdOlScWOHcunpUk21uab1jW7C1deBQARHtKMcuqg="
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"
  d3:
    integrity:
      js: "sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw="
    url:
      js: "https://cdn.jsdelivr.net/npm/d3@7.9.0/dist/d3.min.js"
  diff2html:
    integrity:
      css: "sha256-IMBK4VNZp0ivwefnf2TNnNLMCZAXqtUFnGMhFKBRFkY="
      js: "sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF5bKEUQFIqg="
    url:
      css: "https://cdn.jsdelivr.net/npm/diff2html@3.4.48/bundles/css/diff2html.min.css"
      js: "https://cdn.jsdelivr.net/npm/diff2html@3.4.48/bundles/js/diff2html-ui.min.js"
  echarts:
    integrity:
      js:
        library: "sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY="
        dark_theme: "sha256-sm6Ui9w41++ZCWmIifeIfjtVILCVql8sKBpdNL3jGAA="
    url:
      js:
        library: "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"
        dark_theme: "https://cdn.jsdelivr.net/npm/echarts@5.5.1/themes/dark.js"
  highlight:
    integrity:
      css:
        light: "sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fkNly+/HOkiLEs="
        dark: "sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk="
    url:
      css:
        light: "https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/github.min.css"
        dark: "https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/github-dark.min.css"
  imagesloaded:
    integrity:
      js: "sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc="
    url:
      js: "https://cdn.jsdelivr.net/npm/imagesloaded@5.0.0/imagesloaded.pkgd.min.js"
  img-comparison-slider:
    integrity:
      css: "sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8="
      js: "sha256-EXHg3x1K4oIWdyohPeKX9iP6AmzmkR/X0gFHLJTCgNI="
    url:
      css: "https://cdn.jsdelivr.net/npm/img-comparison-slider@8.0.6/dist/styles.min.css"
      js: "https://cdn.jsdelivr.net/npm/img-comparison-slider@8.0.6/dist/index.min.js"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"
  leaflet:
    integrity:
      css: "sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
      js: "sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV/XN/WPcM="
    url:
      css: "https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.css"
      js: "https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.js"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
  mermaid:
    integrity:
      js: "sha256-TtLOdUA8mstPoO6sGvHIGx2ceXrrX4KgIItO06XOn8A="
    url:
      js: "https://cdn.jsdelivr.net/npm/mermaid@11.2.1/dist/mermaid.min.js"
  medium-zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+asM="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@1.1.0/dist/medium-zoom.min.js"
  swiper:
    integrity:
      css: "sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E="
      js: "sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E="
    url:
      css: "https://cdn.jsdelivr.net/npm/swiper@11.1.14/swiper-bundle.min.css"
      js: "https://cdn.jsdelivr.net/npm/swiper@11.1.14/swiper-bundle.min.js"
  vega:
    integrity:
      js: "sha256-Ovl2M+vg3DLRM9p2I0yFYT3eDOYVcJfAFMNhQ0XHWPE="
      vega-embed: "sha256-FQOL4vt8KO/oOHCCRMtHXfzFhTJ/8q2sJCKIWsCWKoM="
      vega-lite: "sha256-TqDkBDNAOAMTCdRpwGkoFtMEXuXeMnmWDmFu/MtZm8s="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega@5.30.0/build/vega.min.js"
      vega-embed: "https://cdn.jsdelivr.net/npm/vega-embed@6.26.0/build/vega-embed.min.js"
      vega-lite: "https://cdn.jsdelivr.net/npm/vega-lite@5.20.1/build/vega-lite.min.js"